import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { ReduxProvider } from "../redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <nav>
            <Link href="/">
              Home
            </Link>
            <Link href="/notes">
              Notes
            </Link>
          </nav>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </main>
      </body>
    </html>
  );
}
